# Generated by Django 5.1.2 on 2024-11-02 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theatreuserprofile',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='theatreuserprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
