# Generated by Django 5.1.2 on 2024-11-02 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_theatreuserprofile_location_theatreuserprofile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theatreuserprofile',
            name='location',
        ),
        migrations.RemoveField(
            model_name='theatreuserprofile',
            name='name',
        ),
    ]
