# Generated by Django 5.1.2 on 2024-11-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customeruserprofile_city_customeruserprofile_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeruserprofile',
            name='email',
        ),
    ]
