# Generated by Django 5.1.2 on 2024-11-05 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ticket_booking', 'Ticket Booking'), ('food_ordering', 'Food Ordering'), ('fund_transfer', 'Fund Transfer')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('INCOMPLETE', 'Incomplete'), ('COMPLETE', 'Complete'), ('REVERTED', 'Reverted')], default='INCOMPLETE', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('receiver_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='transactions.wallet')),
                ('sender_wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='transactions.wallet')),
            ],
        ),
    ]
