# Generated by Django 5.1.2 on 2024-11-05 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_rename_transaction_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='receiver_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='transactions.wallet'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='sender_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='transactions.wallet'),
        ),
    ]
