# Generated by Django 5.1.2 on 2024-11-04 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0004_show'),
        ('users', '0005_remove_customeruserprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='theatre',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.theatreuserprofile'),
        ),
    ]
