# Generated by Django 5.2 on 2024-11-05 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0005_show_theatre'),
        ('users', '0005_remove_customeruserprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_seats', models.IntegerField()),
                ('status', models.CharField(default='Booked', max_length=20)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketbooking.show')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customeruserprofile')),
            ],
        ),
    ]
