# Generated by Django 5.1.2 on 2024-11-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketbooking', '0006_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screen',
            name='available_seats',
        ),
        migrations.AddField(
            model_name='show',
            name='available_seats',
            field=models.IntegerField(default=0),
        ),
    ]
